### ISSUE TITLE
Accessing to ixp management interface from remote machine

### ISSUE THREAD

**Issue by leostereo** [inex/ixp-manager-docker#1]
Im running ixp manager on  remote docker enviroment.
When trying to connect to http://[server_ip]:8880 it redirects to http://localhost:8880/auth/login and of course it fails accessing.
At first I thought it was related to my browser but after trying on different clients it has same behaviour.
Is there some whay to avoid this redirection ? 
 btw , im trying following docker:
 [https://github.com/inex/ixp-manager-docker](url)
 Regards.

**Comment by barryo** [comment]
Hi @leostereo,

firstly, just FYI, the Docker system as defined in this repo is designed and used only for development purposes. And then only rarely when we need to do some work with, for example, route servers. We are not Docker experts by any means.

The best suggestion I can make on what you've provided is to update the `APP_URL` setting in the `.env` file to something like `http://[server_ip]:8880` - that should hopefully fix the redirect URL.

**Comment by leostereo** [comment]
Hi , @barryo , thank for your words.
BTW : I just need to take a quick look to the system.
Where should I find this .env file ? 
Im trying to find it on  ixpmanager/www:4.7.1 container.
Regards.

**Comment by barryo** [comment]
Oh, 4.7.1. That's really old by the way. Just to reiterate - this is a dev tool only.

`.env.` should be in the root of the IXP Manager source dir. Usually `/srv/ixpmanager`.
